apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-db
  template:
    metadata:
      labels:
        app: catalog-db
    spec:
      containers:
      - name: catalog-db
        image: mongo
        resources:
          requests:
            memory: "64Mi"
            cpu: ".1"
          limits:
            memory: "128Mi"
            cpu: ".3"
        ports:
        - containerPort: 27017
        env:
         - name: MONGO_INITDB_ROOT_USERNAME
           value: username                  
         - name: MONGO_INITDB_ROOT_PASSWORD
           value: password

---
apiVersion: v1
kind: Service
metadata:
  name: catalogdb
spec:
 # type: NodePort
  selector:
    app: catalog-db
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
