apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-webstatus-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop-webstatus
  template:
    metadata:
      labels:
        app: shop-webstatus
    spec:
      containers:
      - name: shop-webstatus
        image: shoppingacr2022.azurecr.io/shopwebstatus:v1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: ".1"
          limits:
            memory: "128Mi"
            cpu: ".3"
        ports:
        - containerPort: 80
        env:
          - name: HealthChecksUI__HealthChecks__0__Name
            value: Catalog Health Check
          - name: HealthChecksUI__HealthChecks__0__Uri
            value: http://catalog-api:8000/hc
          - name: HealthChecksUI__HealthChecks__1__Name
            value: Basket Health Check
          - name: HealthChecksUI__HealthChecks__1__Uri
            value: http://basket-api/hc
          - name: HealthChecksUI__HealthChecks__2__Name
            value: Discount Health Check
          - name: HealthChecksUI__HealthChecks__2__Uri
            value: http://discount-api:8002/hc
          - name: HealthChecksUI__HealthChecks__3__Name
            value: Ordering Health Check
          - name: HealthChecksUI__HealthChecks__3__Uri
            value: http://ordering-api:8004/hc
          - name: HealthChecksUI__HealthChecks__4__Name
            value: Shopping Aggregator Health Check
          - name: HealthChecksUI__HealthChecks__4__Uri
            value: http://shopingaggregator:8005/hc
          - name: HealthChecksUI__HealthChecks__5__Name
            value: AspnetRunBasics WebMVC Health Check
          - name: HealthChecksUI__HealthChecks__5__Uri
            value: http://shop-client/hc
      imagePullSecrets:
        - name: acr-secret              
      
---
apiVersion: v1
kind: Service
metadata:
  name: shop-webstatus
spec:
  type: LoadBalancer
  selector:
    app: shop-webstatus
  ports:
  - port: 80
    # targetPort: 80
    # nodePort: 31007
