apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop-client
  template:
    metadata:
      labels:
        app: shop-client
    spec:
      containers:
        - name: shop-client
          image: shoppingacr2022.azurecr.io/shopclient:v1
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: ".1"
            limits:
              memory: "128Mi"
              cpu: ".3"
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ApiSettings__GatewayAddress
              valueFrom:
                configMapKeyRef:
                  name: shoppingapp-configmap
                  key: ocelotapigw_url
            - name: ElasticConfiguration__Uri
              valueFrom:
                  configMapKeyRef:
                    name: shoppingapp-configmap
                    key: elasticsearch_url
      imagePullSecrets:
        - name: acr-secret              
---
apiVersion: v1
kind: Service
metadata:
  name: shop-client
spec:
  type: LoadBalancer
  selector:
    app: shop-client
  ports:
    - port: 80
      # targetPort: 80
      # nodePort: 31006
