apiVersion: apps/v1
kind: Deployment
metadata:
  name: basket-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basket-api
  template:
    metadata:
      labels:
        app: basket-api
    spec:
      containers:
        - name: basket-api
          image: shoppingacr2022.azurecr.io/basketapi:v1
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: ".1"
            limits:
              memory: "128Mi"
              cpu: ".3"
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: CacheSettings__ConnectionString
              value: basketdb:6379
            - name: GrpcSettings__DiscountUrl
              value: http://discount.grpc
            - name: EventBusSettings__HostAddress
              value: amqp://guest:guest@rabbitmq:5672
            - name: ElasticConfiguration__Uri
              valueFrom:
                configMapKeyRef:
                  name: shoppingapp-configmap
                  key: elasticsearch_url
      imagePullSecrets:
        - name: acr-secret          
---
apiVersion: v1
kind: Service
metadata:
  name: basket-api
spec:
  #type: NodePort
  selector:
    app: basket-api
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 80
      #nodePort: 31001
