apiVersion: apps/v1
kind: Deployment
metadata:
  name: discount-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discount-api
  template:
    metadata:
      labels:
        app: discount-api
    spec:
      containers:
      - name: discount-api
        image: shoppingacr2022.azurecr.io/discountapi:v1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: ".1"
          limits:
            memory: "128Mi"
            cpu: ".3"
        ports:
        - containerPort: 80
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: DatabaseSettings__ConnectionString  
            value: Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;
          - name: ElasticConfiguration__Uri
            valueFrom:
                  configMapKeyRef:
                    name: shoppingapp-configmap
                    key: elasticsearch_url
      imagePullSecrets:
        - name: acr-secret              
---
apiVersion: v1
kind: Service
metadata:
  name: discount-api
spec:
  #type: NodePort
  selector:
    app: discount-api
  ports:
  - port: 8002
    targetPort: 80
   # nodePort: 31002
            
