apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-api
  template:
    metadata:
      labels:
        app: catalog-api
    spec:
      containers:
      - name: catalog-api
        image: sharadit/catalogapi:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: DatabaseSettings__ConnectionString 
            value: mongodb://username:password@catalogdb:27017
          - name: ElasticConfiguration__Uri
            valueFrom:
                  configMapKeyRef:
                    name: shoppingapp-configmap
                    key: elasticsearch_url
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-api
spec:
  type: NodePort
  selector:
    app: catalog-api
  ports:
  - port: 8000
    targetPort: 80
    nodePort: 31000
