apiVersion: apps/v1
kind: Deployment
metadata:
  name: basket-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basket-api
  template:
    metadata:
      labels:
        app: basket-api
    spec:
      containers:
        - name: basket-api
          image: sharadit/basketapi:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: CacheSettings__ConnectionString
              value: basketdb:6379
            - name: GrpcSettings__DiscountUrl
              value: http://discount.grpc
            - name: EventBusSettings__HostAddress
              value: amqp://guest:guest@rabbitmq:5672
            - name: ElasticConfiguration__Uri
              value: http://elasticsearch:9200   

---
apiVersion: v1
kind: Service
metadata:
  name: basket-api
spec:
  type: NodePort
  selector:
    app:  basket-api
  ports:
   - protocol: TCP
     port: 8001
     targetPort: 80
     nodePort: 31001

