apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocelotapigw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocelotapigw
  template:
    metadata:
      labels:
        app: ocelotapigw
    spec:
      containers:
      - name: ocelotapigw
        image: sharadit/ocelotapigw:latest
        # resources:
        #   requests:
        #     memory: "64Mi"
        #     cpu: "250m"
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: ElasticConfiguration__Uri
            valueFrom:
                  configMapKeyRef:
                    name: shoppingapp-configmap
                    key: elasticsearch_url
---
apiVersion: v1
kind: Service
metadata:
  name: ocelotapigw
spec:
  type: NodePort
  selector:
    app: ocelotapigw
  ports:
  - port: 8010
    targetPort: 80
    nodePort: 31010        
