apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop-client
  template:
    metadata:
      labels:
        app: shop-client
    spec:
      containers:
      - name: shop-client
        image: sharadit/shopclient:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: ApiSettings__GatewayAddress
            value: http://ocelotapigw
          - name: ElasticConfiguration__Uri
            value: http://elasticsearch:9200
---
apiVersion: v1
kind: Service
metadata:
  name: shop-client
spec:
  type: NodePort
  selector:
    app: shop-client
  ports:
  - port: 8006
    targetPort: 80
    nodePort: 31006            
