version: '3.4'

services:
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile


  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile


  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile


  shop.client:
    image: ${DOCKER_REGISTRY-}shopclient
    build:
      context: .
      dockerfile: WebApps/Shop.Client/Dockerfile


  shop.webstatus:
    image: ${DOCKER_REGISTRY-}shopwebstatus
    build:
      context: .
      dockerfile: WebApps/Shop.WebStatus/Dockerfile

